import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

@Schema({ timestamps: true })
export class Order extends Document {
  // Remove the @Prop for _id to let MongoDB auto-generate it
  
  @Prop({ type: String, required: true })
  school_id: string;

  @Prop({ type: String, required: false })
  trustee_id: string;

  @Prop({
    type: {
      name: { type: String, required: true },
      id: { type: String, required: true },
      email: { type: String, required: true },
    },
    required: true,
  })
  student_info: {
    name: string;
    id: string;
    email: string;
  };

  @Prop({ type: String, required: false })
  gateway_name: string;
  
  @Prop({ type: String, required: true, index: true })
  collect_request_id: string; // Store the payment gateway's unique ID
}

export const OrderSchema = SchemaFactory.createForClass(Order);

// Add index on _id for efficient querying
// OrderSchema.index({ _id: 1 }); this cannot be used as it is auto-generated by MongoDB

OrderSchema.index({ school_id: 1 }); // For filtering by school
OrderSchema.index({ collect_request_id: 1 }, { unique: true }); // For fast lookups